baseURL = "http://example.org/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "ATAP - Australian Text Analytics Platform"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.2.X"


[menu]
  [[menu.main]]
    identifier = "home"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Home"
    url = "/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "Blog posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Blog"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "text_analysis"
    pre = ""
    post = ""
    name = "Text Analysis"
    url = "/text_analysis/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "resources"
    pre = ""
    post = ""
    name = "Resources"
    url = "more_src.md"
    title = ""
    weight = 4
  [[menu.main]]
    identifier = "organisation"
    pre = ""
    post = ""
    name = "Organisation"
    url = "/organisation.md"
    title = ""
    weight = 5

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
