baseURL = ""
canonifyURLs = true
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "LDaCA - Language Data Commons of Australia"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

enableRobotsTXT = true

[params]
  #  LoveIt theme version
  version = "0.2.X"
  # site description
  description = "Introducing the Language Data Commons of Australia."
  # site keywords
  keywords = ["Theme", "Hugo"]
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  gitRepo = ""
  #  which hash function used for SRI, when empty, no SRI is used
  # ("sha256", "sha384", "sha512", "md5")
  fingerprint = ""
  #  date format
  dateFormat = "02 Jan 2006"
  # website images for Open Graph and Twitter Cards
  images = ["/logo.png"]


  #  Search config
  [params.search]
    enable = true
    # type of search engine ("lunr", "algolia")
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    #  max number of results length
    maxResultLength = 10
    #  snippet length of the result
    snippetLength = 30
    #  HTML tag name of the highlight part in results
    highlightTag = "em"
    #  whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
  [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

# Social config about the author
  [params.social]
    Twitter = "@LTR_Aus"
      
#  social share links in post page
[params.page.share]
      enable = true
      Twitter = true
#  enable nested menus
[params.nested_menus]
      enable = true

[taxonomies]
  tag = 'tags'
  topic = 'topics'
  

[menu]
  [[menu.main]]
    identifier = "home"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Home"
    url = "index.html"
    # title will be shown when you hover on this menu link
    title = "Home"
    weight = 1
  [[menu.main]]
    identifier = "blog posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Blog"
    url = "posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "language data"
    pre = ""
    post = ""
    name = "Language Data"
    url = "data/"
    title = "Language Data"
    weight = 3
  [[menu.main]]
    identifier = "principles"
    pre = ""
    post = ""
    name = "Principles"
    url = "/principles/"
    title = "Principles"
    weight = 1
    parent = "language data"
  [[menu.main]]
    identifier = "technologies"
    pre = ""
    post = ""
    name = "Technologies"
    url = "/technologies/"
    title = "Technologies"
    weight = 2
    parent = "language data"
     [[menu.main]]
    identifier = "metadata"
    pre = ""
    post = ""
    name = "Metadata"
    url = "/metadata/"
    title = "Metadata"
    weight = 3
    parent = "language data"
  [[menu.main]]
    identifier = "sample-collections"
    pre = ""
    post = ""
    name = "Sample Collections"
    url = "/collections/"
    title = "Sample Collections"
    weight = 4
    parent = "language data"
    [[menu.main]]
    identifier = "case-studies"
    pre = ""
    post = ""
    name = "Case Studies"
    url = "/case-studies/"
    title = "Case Studies"
    weight = 5
    parent = "language data"
    [[menu.main]]
      [[menu.main]]
    identifier = "resources"
    pre = ""
    post = ""
    name = "Resources"
    url = "resources/"
    title = ""
    weight = 4
  [[menu.main]]
    identifier = "organisation"
    pre = ""
    post = ""
    name = "Organisation"
    url = "organisation/"
    title = ""
    weight = 5


# Markup related config in Hugo
[markup]
  # Syntax Highlighting
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author config
[author]
  name = "Language Data Commons of Australia"
  email = "info @ ldaca.edu.au"
  link = "http://www.ldaca.edu.au"

# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks config
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

# Privacy config
[privacy]
  #  privacy of the Google Analytics (replaced by params.analytics.google)
  [privacy.googleAnalytics]
    # ...
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  #
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
