// This file previously used Node fs to build a pages map at module load,
// which caused bundling errors when imported into client-side code.
// Keep a safe empty export here — real data is provided by the
// virtual:pages-data module generated by .vitepress/config.ts.

export const data: Record<string, any> = {}
